# Generated by Django 5.2.6 on 2025-10-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millet_type', models.CharField(choices=[('pearl', 'Pearl Millet (Bajra)'), ('finger', 'Finger Millet (Ragi)'), ('foxtail', 'Foxtail Millet'), ('proso', 'Proso Millet'), ('kodo', 'Kodo Millet'), ('barnyard', 'Barnyard Millet'), ('little', 'Little Millet'), ('sorghum', 'Sorghum (Jowar)'), ('other', 'Other Millet')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('advisory_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_advisories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('grain', 'Grain'), ('flour', 'Flour'), ('snack', 'Snack'), ('ready_to_eat', 'Ready to Eat'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_organic', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
